#!/usr/bin/env python

"""dbx: Dropbox Revision Control

Usage: 
  dbx init
  dbx commit (MESSAGE)
  dbx checkout (REVISION)
  dbx log

Options:
  -h --help     Display this message and exit

"""

import os, re
from docopt import docopt
from os import path
import re
from ConfigParser import ConfigParser
from dbxscm import Datastore, Revision

def init():
  parser = ConfigParser()
  parser.add_section('dbx')
  name = path.split(os.getcwd())[1]
  parser.set('dbx', 'name', name)
  with open(path.abspath('.dbx'), 'w') as writer:
    parser.write(writer)

  print 'dbx repository initialized at: %s' % path.abspath('.')

def commit(message):
  r = Revision()
  root = r.parser.get('general', 'home')
  path = re.findall("%s/(.*)" % root, os.getcwd())[0]
  r.snapshot_revisions(path)

def checkout(revision):
  pass

def log():
  pass

if __name__ == "__main__":
  arguments = docopt(__doc__) 

  if arguments.get('init'):
    init()

  if arguments.get('commit'):
    commit(arguments['MESSAGE'])
